job: extension
config:
  name: nowy_dataset

  process:
    - type: sd_trainer
      training_folder: "/workspace/output"
      device: cuda:0

      network:
        type: lora
        linear: 16
        linear_alpha: 16

      save:
        dtype: float16
        save_every: 1000
        max_step_saves_to_keep: 1
        push_to_hub: false

      datasets:
        - folder_path: "/workspace/training_data"
          caption_ext: txt
          caption_dropout_rate: 0.05
          shuffle_tokens: false
          cache_latents_to_disk: true
          resolution: [512, 768, 1024, 1280]  # <-- Dodano 1280 pod proporcje 4:5

      train:
        batch_size: 2
        steps: 2000
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        noise_scheduler: flowmatch
        optimizer: adamw8bit
        lr: 0.0001
        ema_config:
          use_ema: true
          ema_decay: 0.99
        dtype: bf16

      model:
        name_or_path: "black-forest-labs/FLUX.1-dev"
        is_flux: true
        quantize: true

      sample:
        sampler: flowmatch
        sample_every: 100
        width: 1024               # <-- Szerokość 1024
        height: 1280              # <-- Wysokość 1280 (4:5 proporcja)
        prompts:
          - "Photo of Mateusz"
        neg: ""
        seed: 42
        walk_seed: true
        guidance_scale: 4
        sample_steps: 20